defaultIndent: "  "
noAdditionalIndent:
  problem: 0
  problem-t: 0
  inlineMath: 0
  subproblems: 1
  itemize: 1
  enumerate: 1
  ifflist: 1
indentRules:
  inlineMath: "  "
  item: "  "
indentAfterItems:
  subproblems: 1
  ifflist: 1
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    removeBlockLineBreaks: 1
    multipleSpacesToSingle: 1
    when: "before"
    comments:
      wrap: 0
    blocksFollow:
      other: 0
      other: |
        (?x)
        \\begin\{(?:problem(?:-[tc])?|solution)\}(?:\[[0-9A-Za-z _\-=,.]*\])?
        |
        \\]
        |
        \\end\{align\*?\}
        |
        \\(?:begin|end)\{(?:itemize\*?|enumerate\*?|description\*?|subproblems\*?|aside|center)\}
        |
        \\intertext\{
        |
        \\item(?:\[.*\])?\ +
    blocksBeginWith:
      other: |
        (?x)
        \\\(
        |
        \(
        |
        \\emph\{
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 0
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
fineTuning:
  environments:
    name: '[0-9A-Za-z_\-@\*]+'
